In [3]:
import torch

In [5]:
t = torch.tensor([11,22,33,44,55])

# 인덱싱

In [8]:
t[0].item()

11

In [10]:
t[-1].item()

55

## 복수개 인덱싱
- [[인덱스,....]]

In [24]:
t[[1,3,4]]

tensor([22, 44, 55])

#### 슬라이싱
- [시작인덱스:끝인덱스:증가치]
- 시작인덱스 <= index < 끝인덱스

In [11]:
t[1:3:1] # 1<=idx<3 1,2

tensor([22, 33])

In [14]:
t[1:3:1].numpy()

array([22, 33], dtype=int64)

In [15]:
t[1:3]

tensor([22, 33])

In [16]:
t[2:]

tensor([33, 44, 55])

### 2차원 인덱싱 슬라이싱
- [행]
- [행, 열]

### 3차원 인덱싱 슬라이싱
- [면]
- [면, 행]
- [면, 행, 열]

In [18]:
tt = torch.tensor([[11,22],[33,44],[55,66]]) # 3 x 2
tt

tensor([[11, 22],
        [33, 44],
        [55, 66]])

In [19]:
tt[0]

tensor([11, 22])

In [21]:
tt[0,1]

tensor(22)

In [23]:
tt[1:]

tensor([[33, 44],
        [55, 66]])

In [22]:
tt[1:, 1:]

tensor([[44],
        [66]])