In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x1 = torch.FloatTensor([1,0,3,4,5]) # 공부한 시간
x2 = torch.FloatTensor([0,1,2,3,4]) # 출석 일수
y = torch.FloatTensor([1,2,3,4,5]) # 출석 점수

In [3]:
w1 = torch.empty(1, requires_grad=True)
w2 = torch.empty(1, requires_grad=True)
b = torch.empty(1, requires_grad=True)
torch.nn.init.uniform_(w1)
torch.nn.init.uniform_(w2)
torch.nn.init.uniform_(b)

tensor([0.2773], requires_grad=True)

In [4]:
def cost():
    hx = w1*x1 + w2*x2 +b
    c = torch.mean((hx-y)**2)
    return c

In [7]:
optimizer = Adam([w1, w2, b], lr = 0.01)
for epoch in range(1000):
    c = cost()
    optimizer.zero_grad()
    c.backward()
    optimizer.step()
    print(epoch, c.item())

0 1.1195353269577026
1 1.0078518390655518
2 0.9047505259513855
3 0.8103524446487427
4 0.7247289419174194
5 0.6478936076164246
6 0.5797902345657349
7 0.5202816724777222
8 0.46913808584213257
9 0.4260297417640686
10 0.3905143737792969
11 0.36204004287719727
12 0.3399469554424286
13 0.32348307967185974
14 0.3118271231651306
15 0.3041204810142517
16 0.2995041310787201
17 0.2971530556678772
18 0.2963085472583771
19 0.2963002920150757
20 0.2965618968009949
21 0.2966383099555969
22 0.2961863577365875
23 0.29497069120407104
24 0.29285481572151184
25 0.28978973627090454
26 0.2858000695705414
27 0.28096961975097656
28 0.2754254937171936
29 0.2693237364292145
30 0.26283499598503113
31 0.2561325430870056
32 0.2493811845779419
33 0.2427290380001068
34 0.23630090057849884
35 0.23019453883171082
36 0.2244781255722046
37 0.2191905975341797
38 0.21434304118156433
39 0.20992207527160645
40 0.2058938443660736
41 0.20220907032489777
42 0.1988084465265274
43 0.19562751054763794
44 0.19260188937187195
45 0.

478 0.00021896150428801775
479 0.00021483928139787167
480 0.00021078965801279992
481 0.00020681010209955275
482 0.00020290203974582255
483 0.00019906085799448192
484 0.00019528655684553087
485 0.00019157947099301964
486 0.00018793615163303912
487 0.00018435883976053447
488 0.00018084341718349606
489 0.00017739049508236349
490 0.000173998560057953
491 0.00017066646250896156
492 0.000167392790899612
493 0.00016418020823039114
494 0.0001610226754564792
495 0.0001579220115672797
496 0.00015487722703255713
497 0.00015188656107056886
498 0.00014894906780682504
499 0.00014606349577661604
500 0.0001432306889910251
501 0.00014044971612747759
502 0.00013771880185231566
503 0.00013503768423106521
504 0.00013240476255305111
505 0.00012981821782886982
506 0.00012727997091133147
507 0.00012478596181608737
508 0.000122340046800673
509 0.00011993829684797674
510 0.0001175788784166798
511 0.00011526326125022024
512 0.00011299129982944578
513 0.00011075926158810034
514 0.00010856853623408824
515 0.00010

879 1.1027205815139496e-08
880 1.0683436357794562e-08
881 1.0362475322267528e-08
882 1.004525529424427e-08
883 9.750283247456082e-09
884 9.439910186870293e-09
885 9.161499114895832e-09
886 8.886106961369933e-09
887 8.614927438088671e-09
888 8.34650126790848e-09
889 8.096710857330436e-09
890 7.849041416818636e-09
891 7.608539576153817e-09
892 7.372784605053084e-09
893 7.151314207476389e-09
894 6.9312817707611885e-09
895 6.721444290036516e-09
896 6.5210770117118955e-09
897 6.31438590303901e-09
898 6.12456307891307e-09
899 5.927998536492396e-09
900 5.744300146659498e-09
901 5.56963453135495e-09
902 5.396535218693543e-09
903 5.230464061867224e-09
904 5.069455077943985e-09
905 4.909785022988444e-09
906 4.761397942587564e-09
907 4.604459036272601e-09
908 4.468645897759416e-09
909 4.32510205428116e-09
910 4.190144231586146e-09
911 4.058529068373673e-09
912 3.9320782185825465e-09
913 3.81347708966473e-09
914 3.691948746720186e-09
915 3.5763179084824515e-09
916 3.4645524227272517e-09
917 3.3556

In [9]:
w1

tensor([1.8937e-05], requires_grad=True)

In [10]:
w2 

tensor([1.0000], requires_grad=True)

In [11]:
b

tensor([1.0000], requires_grad=True)

In [12]:
w1*5 + w2*5 + b

tensor([6.0000], grad_fn=<AddBackward0>)