In [10]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential, Sigmoid
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn.functional as F

In [2]:
x = torch.FloatTensor([[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]]) # 공부한시간, 출석일수
y = torch.FloatTensor([[0],[0],[0],[1],[1],[1]]) # 합격여부

In [5]:
w = torch.empty([2,1], requires_grad=True)
b = torch.empty(1, requires_grad=True)
torch.nn.init.uniform_(w)
torch.nn.init.uniform_(b)

tensor([0.0361], requires_grad=True)

In [9]:
def cost():
    z = torch.matmul(x,w) + b
    cost_i = F.binary_cross_entropy_with_logits(z, y)
    c = torch.mean(cost_i)
    return c

In [12]:
def cost1():
    z = torch.matmul(x,w) + b
    hx = Sigmoid(z)
    cost_i = F.binary_cross_entropy(hx, y)
    c = torch.mean(cost_i)
    return c

In [14]:
optimizer = Adam([w,b], lr=0.01)
for epoch in range(1000):
    c = cost()
    optimizer.zero_grad()
    c.backward()
    optimizer.step()
    print('cost=', c.item())

cost= 0.10128452628850937
cost= 0.10088306665420532
cost= 0.10044869035482407
cost= 0.10004209727048874
cost= 0.09965848922729492
cost= 0.09924623370170593
cost= 0.09883362799882889
cost= 0.09844060987234116
cost= 0.09804984927177429
cost= 0.09764891117811203
cost= 0.09725076705217361
cost= 0.09686412662267685
cost= 0.0964793786406517
cost= 0.09608874469995499
cost= 0.09569796174764633
cost= 0.09531420469284058
cost= 0.09493502229452133
cost= 0.09455418586730957
cost= 0.09417257457971573
cost= 0.09379539638757706
cost= 0.09342280775308609
cost= 0.09305057674646378
cost= 0.09267749637365341
cost= 0.09230678528547287
cost= 0.09194017201662064
cost= 0.09157553315162659
cost= 0.09121104329824448
cost= 0.09084818512201309
cost= 0.09048864245414734
cost= 0.09013151377439499
cost= 0.08977507799863815
cost= 0.08941986411809921
cost= 0.08906734734773636
cost= 0.08871734142303467
cost= 0.08836858719587326
cost= 0.08802122622728348
cost= 0.08767616748809814
cost= 0.08733349293470383
cost= 0.08699

cost= 0.024048427119851112
cost= 0.02399834245443344
cost= 0.023948408663272858
cost= 0.023898646235466003
cost= 0.023849016055464745
cost= 0.023799538612365723
cost= 0.023750247433781624
cost= 0.02370109222829342
cost= 0.023652084171772003
cost= 0.023603230714797974
cost= 0.023554550483822823
cost= 0.02350602112710476
cost= 0.0234576016664505
cost= 0.023409375920891762
cost= 0.02336127869784832
cost= 0.023313315585255623
cost= 0.023265546187758446
cost= 0.023217884823679924
cost= 0.02317039854824543
cost= 0.02312302775681019
cost= 0.023075824603438377
cost= 0.02302875556051731
cost= 0.022981835529208183
cost= 0.0229350533336401
cost= 0.022888438776135445
cost= 0.022841935977339745
cost= 0.02279558777809143
cost= 0.022749392315745354
cost= 0.02270331047475338
cost= 0.022657399997115135
cost= 0.022611619904637337
cost= 0.022565996274352074
cost= 0.022520482540130615
cost= 0.0224751029163599
cost= 0.022429876029491425
cost= 0.022384779527783394
cost= 0.022339841350913048
cost= 0.02229501

cost= 0.012702230364084244
cost= 0.01268297340720892
cost= 0.012663832865655422
cost= 0.012644669972360134
cost= 0.012625587172806263
cost= 0.012606523931026459
cost= 0.012587536126375198
cost= 0.012568589299917221
cost= 0.012549680657684803
cost= 0.01253077294677496
cost= 0.012511920183897018
cost= 0.012493127025663853
cost= 0.012474394403398037
cost= 0.012455698102712631
cost= 0.012437003664672375
cost= 0.012418404221534729
cost= 0.012399786151945591
cost= 0.012381265871226788
cost= 0.012362743727862835
cost= 0.012344281189143658
cost= 0.012325855903327465
cost= 0.012307490222156048
cost= 0.012289144098758698
cost= 0.012270835228264332
cost= 0.012252586893737316
cost= 0.012234334833920002
cost= 0.012216162867844105
cost= 0.012198030948638916
cost= 0.012179934419691563
cost= 0.012161859311163425
cost= 0.012143862433731556
cost= 0.012125884182751179
cost= 0.012107905931770802
cost= 0.012090024538338184
cost= 0.012072182260453701
cost= 0.01205432042479515
cost= 0.012036575935781002
cost

In [15]:
w

tensor([[1.5582],
        [1.5582]], requires_grad=True)

In [31]:
def hxFn(xd):
    xd = torch.FloatTensor(xd)
    z = torch.matmul(xd, w) + b
    hx = torch.sigmoid(z)
#     return z, hx
#     return ((hx > 0.5) + 0).detach().item() # True + 1 = 2 , True + 0 = 1, False + 1 = 1, False + 0 = 0
    return ((hx > 0.5) + 0).detach().numpy()

In [33]:
hxFn([[4,5]])

array([[1]], dtype=int64)

In [35]:
pred = hxFn(x)
pred

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)

In [39]:
(y.numpy() == pred).mean() # 정확도

1.0