In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential, Sigmoid, Softmax
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn.functional as F
import seaborn as sb

from sklearn.preprocessing import MinMaxScaler, StandardScaler

import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

In [2]:
softFn = Softmax(dim=1) # 행별 확률값
softFn1 = Softmax(dim=0) # 컬럼별 확률값

In [3]:
r = torch.randn(2,3) # normalized 
r

tensor([[-2.7484,  0.6320,  0.4735],
        [-0.5683, -0.4525,  0.3800]])

In [4]:
softFn(r)

tensor([[0.0180, 0.5298, 0.4522],
        [0.2126, 0.2387, 0.5487]])

In [5]:
softFn1(r)

tensor([[0.1016, 0.7473, 0.5234],
        [0.8984, 0.2527, 0.4766]])

In [6]:
df = pd.read_csv('../data/softmax.txt', sep=' ', header=None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

onehot encoding 0 0 1 => A,  0 1 0 => B, 1 0 0 => C

In [30]:
x_data = df.iloc[:,0:2].values
y_data = df.iloc[:,2:].values

In [31]:
x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

In [32]:
w = torch.empty([2,3], requires_grad=True) # [특성데이터 갯수, 라벨의 갯수]
b = torch.empty([3], requires_grad=True) # 라벨의 겟수
torch.nn.init.uniform_(w)
torch.nn.init.uniform_(b)

tensor([0.2391, 0.0810, 0.8012], requires_grad=True)

In [39]:
y

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])

In [33]:
def cost():
    z = torch.matmul(x, w) + b
#     hx = F.softmax(z, dim=1)
    cost_i = F.cross_entropy(z, y) # cross_entropy에는 softmax가 포함되어 있음
    # xxxx c= torch.mean((hx-y)**2) 
    c = torch.mean(cost_i)
    return c

In [34]:
optimizer = Adam([w,b], lr=0.01)
for epoch in range(1000):
    c = cost()
    optimizer.zero_grad()
    c.backward()
    optimizer.step()
    print('cost: ', c.item())

cost:  1.3787620067596436
cost:  1.306131362915039
cost:  1.2442872524261475
cost:  1.193354606628418
cost:  1.1524877548217773
cost:  1.1197736263275146
cost:  1.0928761959075928
cost:  1.0700523853302002
cost:  1.0505273342132568
cost:  1.0342178344726562
cost:  1.0213329792022705
cost:  1.012068748474121
cost:  1.0063999891281128
cost:  1.0039668083190918
cost:  1.0040576457977295
cost:  1.0057013034820557
cost:  1.0078375339508057
cost:  1.0095247030258179
cost:  1.0100996494293213
cost:  1.009248971939087
cost:  1.0069851875305176
cost:  1.0035650730133057
cost:  0.9993812441825867
cost:  0.9948583841323853
cost:  0.9903621673583984
cost:  0.9861375689506531
cost:  0.9822837114334106
cost:  0.978765606880188
cost:  0.9754631519317627
cost:  0.9722341299057007
cost:  0.9689712524414062
cost:  0.9656358957290649
cost:  0.9622621536254883
cost:  0.9589386582374573
cost:  0.9557760953903198
cost:  0.9528735876083374
cost:  0.9502900838851929
cost:  0.9480297565460205
cost:  0.94603979

cost:  0.6150269508361816
cost:  0.6144838333129883
cost:  0.6139421463012695
cost:  0.6134017705917358
cost:  0.612862765789032
cost:  0.6123253107070923
cost:  0.6117892265319824
cost:  0.6112543344497681
cost:  0.6107211112976074
cost:  0.6101890802383423
cost:  0.609658420085907
cost:  0.6091291308403015
cost:  0.6086012125015259
cost:  0.6080745458602905
cost:  0.6075493097305298
cost:  0.6070254445075989
cost:  0.606502890586853
cost:  0.6059814095497131
cost:  0.6054614782333374
cost:  0.6049429178237915
cost:  0.6044251918792725
cost:  0.6039091348648071
cost:  0.6033942699432373
cost:  0.602880597114563
cost:  0.6023681163787842
cost:  0.6018569469451904
cost:  0.6013470888137817
cost:  0.6008384227752686
cost:  0.6003308296203613
cost:  0.5998246669769287
cost:  0.599319577217102
cost:  0.5988157987594604
cost:  0.5983133316040039
cost:  0.5978118777275085
cost:  0.5973116159439087
cost:  0.5968124866485596
cost:  0.5963146686553955
cost:  0.5958179831504822
cost:  0.59532237

cost:  0.47650113701820374
cost:  0.47620391845703125
cost:  0.47590696811676025
cost:  0.47561055421829224
cost:  0.4753144085407257
cost:  0.4750187397003174
cost:  0.4747232496738434
cost:  0.47442835569381714
cost:  0.47413370013237
cost:  0.47383934259414673
cost:  0.4735453724861145
cost:  0.4732517600059509
cost:  0.4729584753513336
cost:  0.47266557812690735
cost:  0.47237300872802734
cost:  0.47208085656166077
cost:  0.47178900241851807
cost:  0.47149747610092163
cost:  0.4712064266204834
cost:  0.4709155261516571
cost:  0.47062504291534424
cost:  0.4703349471092224
cost:  0.470045268535614
cost:  0.4697558283805847
cost:  0.4694666862487793
cost:  0.4691780209541321
cost:  0.46888959407806396
cost:  0.46860161423683167
cost:  0.46831387281417847
cost:  0.4680265188217163
cost:  0.46773943305015564
cost:  0.4674528241157532
cost:  0.4671664834022522
cost:  0.4668804407119751
cost:  0.46659472584724426
cost:  0.46630948781967163
cost:  0.4660244584083557
cost:  0.46573984622955

In [35]:
def hxFn(xd):
    xd = torch.FloatTensor(xd)
    z = torch.matmul(xd, w) + b
    hx = torch.softmax(z, dim=1)
    return hx.argmax(dim=1), hx
#     return z, hx

In [36]:
hxFn([[2,3]])

(tensor([2]), tensor([[0.0079, 0.1922, 0.7999]], grad_fn=<SoftmaxBackward0>))

In [38]:
## 6,6 2,2

hxFn([[6,6], [2,2]])

(tensor([0, 2]),
 tensor([[0.5528, 0.4250, 0.0223],
         [0.0010, 0.0660, 0.9330]], grad_fn=<SoftmaxBackward0>))