In [23]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential, Sigmoid, Softmax
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn.functional as F
import seaborn as sb

from sklearn.preprocessing import MinMaxScaler, StandardScaler

import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

In [24]:
df = pd.read_csv('../data/softmax.txt', sep=' ', header=None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [25]:
x_data = df.iloc[:,0:2].values
y_data = df.iloc[:,2:].values

In [26]:
x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

In [27]:
model = Sequential()
model.add_module('nn1', Linear(2,3)) # w: 2x3, b: 3
model.add_module('softmax', Softmax(dim=1)) # 할성함수
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr=0.01)

In [28]:
for epoch in range(2000):
    optimizer.zero_grad()
    hx = model.forward(x) 
    # z = torch.matmul(x,w)+b
    # hx = Softmax(z)
    cost = loss_fn(hx,y)
    cost.backward()
    optimizer.step()
    print(epoch, cost.item())

0 1.218047857284546
1 1.2090193033218384
2 1.1992342472076416
3 1.1887714862823486
4 1.1777923107147217
5 1.1665682792663574
6 1.1555036306381226
7 1.145137071609497
8 1.1360983848571777
9 1.128995418548584
10 1.1242319345474243
11 1.1218215227127075
12 1.1213337182998657
13 1.122054934501648
14 1.1232678890228271
15 1.1244444847106934
16 1.1252822875976562
17 1.1256495714187622
18 1.1255155801773071
19 1.1249022483825684
20 1.123857855796814
21 1.1224451065063477
22 1.1207375526428223
23 1.1188181638717651
24 1.1167792081832886
25 1.1147180795669556
26 1.1127312183380127
27 1.1109046936035156
28 1.1093027591705322
29 1.1079587936401367
30 1.106871485710144
31 1.1060054302215576
32 1.1053013801574707
33 1.1046866178512573
34 1.1040887832641602
35 1.1034460067749023
36 1.1027120351791382
37 1.101860761642456
38 1.1008840799331665
39 1.0997897386550903
40 1.0985971689224243
41 1.0973329544067383
42 1.096027135848999
43 1.0947074890136719
44 1.093398094177246
45 1.0921154022216797
46 1.09

715 0.8144027590751648
716 0.8143435716629028
717 0.8142845034599304
718 0.8142255544662476
719 0.8141669034957886
720 0.8141083717346191
721 0.8140498995780945
722 0.8139916658401489
723 0.8139336109161377
724 0.8138757348060608
725 0.813818097114563
726 0.8137603998184204
727 0.8137030601501465
728 0.8136458396911621
729 0.8135887384414673
730 0.8135318160057068
731 0.8134750127792358
732 0.813418447971344
733 0.8133620619773865
734 0.8133057355880737
735 0.8132495880126953
736 0.813193678855896
737 0.8131377696990967
738 0.8130820989608765
739 0.8130266666412354
740 0.812971293926239
741 0.8129161596298218
742 0.8128610849380493
743 0.8128061890602112
744 0.8127514123916626
745 0.8126968145370483
746 0.8126424551010132
747 0.812588095664978
748 0.812533974647522
749 0.8124800324440002
750 0.8124260902404785
751 0.8123724460601807
752 0.8123189210891724
753 0.8122655153274536
754 0.8122122287750244
755 0.8121590614318848
756 0.8121061325073242
757 0.8120533227920532
758 0.81200063228

1487 0.7923948168754578
1488 0.7923809289932251
1489 0.7923670411109924
1490 0.7923531532287598
1491 0.7923393845558167
1492 0.7923255562782288
1493 0.7923117876052856
1494 0.7922979593276978
1495 0.7922842502593994
1496 0.7922704219818115
1497 0.7922568321228027
1498 0.7922430634498596
1499 0.7922293543815613
1500 0.7922157049179077
1501 0.7922021150588989
1502 0.7921884059906006
1503 0.7921748161315918
1504 0.792161226272583
1505 0.7921475768089294
1506 0.7921341061592102
1507 0.7921205759048462
1508 0.7921069860458374
1509 0.7920935153961182
1510 0.7920800447463989
1511 0.7920665144920349
1512 0.7920531034469604
1513 0.7920396327972412
1514 0.792026162147522
1515 0.7920129299163818
1516 0.7919994592666626
1517 0.7919861078262329
1518 0.7919727563858032
1519 0.7919594049453735
1520 0.7919461727142334
1521 0.7919328212738037
1522 0.7919195890426636
1523 0.7919062376022339
1524 0.7918930649757385
1525 0.7918798327445984
1526 0.791866660118103
1527 0.7918534278869629
1528 0.791840314865

1882 0.7880758047103882
1883 0.7880672216415405
1884 0.7880587577819824
1885 0.7880501747131348
1886 0.7880417108535767
1887 0.7880331873893738
1888 0.7880246639251709
1889 0.7880162000656128
1890 0.7880076766014099
1891 0.7879992127418518
1892 0.7879908084869385
1893 0.7879822850227356
1894 0.7879738807678223
1895 0.7879654169082642
1896 0.7879570126533508
1897 0.7879486083984375
1898 0.7879402041435242
1899 0.7879317998886108
1900 0.7879234552383423
1901 0.7879151105880737
1902 0.7879067063331604
1903 0.7878983020782471
1904 0.7878899574279785
1905 0.78788161277771
1906 0.7878733277320862
1907 0.7878650426864624
1908 0.7878566980361938
1909 0.7878484129905701
1910 0.7878401279449463
1911 0.7878317832946777
1912 0.787823498249054
1913 0.7878152132034302
1914 0.787807047367096
1915 0.7877987623214722
1916 0.7877905368804932
1917 0.7877823114395142
1918 0.7877740859985352
1919 0.7877658605575562
1920 0.7877576351165771
1921 0.7877495288848877
1922 0.7877413034439087
1923 0.7877331376075

In [29]:
model[0].weight

Parameter containing:
tensor([[ 2.5884, -0.0857],
        [-2.9331,  2.1763],
        [ 2.4410, -2.9010]], requires_grad=True)

In [30]:
model[0].bias

Parameter containing:
tensor([-7.1864, -1.4680,  7.6079], requires_grad=True)

In [31]:
p = model.forward(torch.FloatTensor([[5,6]]))
p.argmax(dim=1)

tensor([0])

In [34]:
p = model.forward(torch.FloatTensor([[6,6], [2,2]]))
p.argmax(dim=1)

tensor([0, 2])